### ISSUE TITLE
Analysis could not be completed because of an internal error

### ISSUE THREAD

**Issue by jensasmusclausen** [tabulartools/dax-optimizer#13]
### Describe the problem

Running the analysis on one of the 3 models has failed.

There is no more information than:
Analysis could not be completed because of an internal error. 
Do not try to rerun the analysis, instead report the issue here. 

I hope you can find more information with the Trace id: 0417dbb7-14fa-e0b0-fc44-c2c0245294b2

### Power BI

Power BI 1550

### Anything else ?

Trace id: 0417dbb7-14fa-e0b0-fc44-c2c0245294b2

**Comment by albertospelta** [comment]
Hi @jensasmusclausen, thanks for reporting the issue! 
We are working to resolve the error and will update you when the fix is deployed in production.

**Comment by albertospelta** [comment]
@jensasmusclausen the fix has been deployed to production and you should now be able to re-run the analysis without errors.

![image](https://github.com/tabulartools/dax-optimizer/assets/1957788/2bcb4d58-7ecb-4fa6-b935-ed0c38c5b7b9)

**Comment by jensasmusclausen** [comment]
Thank you for your help. It works fine, just low issues found :-)

**Comment by marcosqlbi** [comment]
@jensasmusclausen please do not consider "low" as "not important" as those issues could be the reason for a slow report - they just don't propagate to the entire model.
We are implementing a new UI design where we will remove the "priority" of the issues, creating a single ranking to prioritize the issues to solve.
