### ISSUE TITLE
input contains invalid html tags

### ISSUE THREAD

**Issue by MIS-TF** [tabulartools/dax-optimizer#16]
### Describe the problem

when uploading a VPAX file of a published dataset i get the message:
input contains invalid html tags

no further details were given.

VPAX file was generated by DAX studio 3.0.10
also tried using Tabular Editor 3 build 3.4.8392.26581

not sure if it is relevant but the dataset is 15.90 GB

### Power BI

Power Bi Premium P2 published model

### Steps to reproduce the behavior

upload VPAX file as new model

### Screenshots

![image](https://github.com/tabulartools/dax-optimizer/assets/123965997/2f91dddb-afb4-486d-ab54-9bc4e09427bd)

**Comment by danieleperilli** [comment]
Hi, it seems to be a bug related to ampersands. We will fix it as soon as possible, in the meantime the solution is to remove the & from the model name.

**Comment by danieleperilli** [comment]
A fix has been released.
