### ISSUE TITLE
Function result invariant to current iterator - Incorrect?

### ISSUE THREAD

**Issue by mwardcusd** [tabulartools/dax-optimizer#18]
### Describe the problem

I believe there is a false positive with this check.

### Power BI

SSAS 2019

### Steps to reproduce the behavior

```
VAR CurNum =
    MAX( Numbers[Number] )
VAR ValidEmp =
  FILTER(
    VALUES( vw_SSAS_Employee[EMPLOYEE_BK] ), 
    NOT **ISEMPTY( RELATEDTABLE( 'FCT_SEIS_HISTORY_STUDENT' ) ) **
  )
RETURN
    SUMX(
        ValidEmp,
        IF( INT( [StuPerFTE_JSR] ) = CurNum, 1, BLANK() )
    )
```

### Additional context

It claims that `ISEMPTY( RELATEDTABLE( 'FCT_SEIS_HISTORY_STUDENT' ) )` is invariant, but it isn't. There is a relationship from vw_SSAS_Employee to FCT_SEIS_HISTORY_STUDENT, so the ISEMPTY calculation will be different for each EMPLOYEE_BK. Am I missing something here?

**Comment by albertospelta** [comment]
@mwardcusd thanks for reporting the issue! We have identified the bug and are fixing it.
I'll update you when the fix is deployed in production.

**Comment by albertospelta** [comment]
@mwardcusd I'm closing this issue as the fix has been deployed to production.
If you’re still seeing issues, please feel free to post back here and we can reopen it.
