### ISSUE TITLE
Can't add Licence 

### ISSUE THREAD

**Issue by G-Pichon** [tabulartools/dax-optimizer#19]
### Describe the problem

I can't copy paste the licence I just bought after clicking on "activate licence"

### Power BI

Dax

### Screenshots

<img width="272" alt="Capture d'écran 2023-11-22 092820" src="https://github.com/tabulartools/dax-optimizer/assets/138606513/7421e5ba-16ac-4602-aa4f-6970e89c9105">

**Comment by albertospelta** [comment]
Hi @G-Pichon, we're investigating this and will update this issue.

**Comment by albertospelta** [comment]
@G-Pichon the fix for this issue has been released.

**Comment by G-Pichon** [comment]
Indeed ! Thanks
