### ISSUE TITLE
Can not delete models from old inactive contracts -- junks up the list of models

### ISSUE THREAD

**Issue by rmss-tech** [tabulartools/dax-optimizer#21]
### Describe the problem

Error DO100003: Contract expired.
The contract is expired.
DELETE /v1/model/251707042395-84561f5f-a08c-4ac7-a403-6e3a17588ec6/251707031702-979f7013-6a7d-4323-b376-53ece95c8cb6

### Power BI

September 2023 v2.121.644.0 64-bit

### Anything else ?

Trace id: 7c5d8517d097e80de62fe309ab103e1e

**Comment by albertospelta** [comment]
Thanks for reporting. We are aware that this feature is not currently supported, and we plan to release it shortly, within the next couple of days. I'll update you when the fix is deployed in production.

**Comment by albertospelta** [comment]
@rmss-tech I'm closing this issue as the functionality to delete models from inactive contracts has been released to production. If you still encounter any issues, please feel free to reply here, and we can reopen it. Thanks!
