### ISSUE TITLE
Contract is not at the local day granularity

### ISSUE THREAD

**Issue by jasoncabell** [tabulartools/dax-optimizer#22]
### Describe the problem

Contracts should be at the users local time. I've run multiple analyses today and I see at 9:42 pm, my contract is reset for the next day. This should only reset and Midnight local time.

### Power BI

Power BI Desktop (RS) September 2021

### Steps to reproduce the behavior

upload a new vpax late in the day
the number of analyses should be your contract minutes what you performed that day.
What happens is the contract is reset before midnight.

### Screenshots

![image](https://github.com/tabulartools/dax-optimizer/assets/44036650/3eb31573-c8f1-4bf1-94d9-0d1a8d74078e)

**Comment by marcosqlbi** [comment]
Hi Jason,

thank you for reporting the issue! We are evaluating how to manage that; probably, we should assign the timezone to the license. I'll keep you posted!

**Comment by albertospelta** [comment]
@jasoncabell I can confirm that we are working to add the ability to assign a timezone to contracts. We will provide further details as soon as this feature is available, likely within a couple of weeks.

**Comment by albertospelta** [comment]
@jasoncabell the feature has been released. Now, you can assign a time zone to a license, enabling you to determine the reset of daily runs based on your preferred time zone. I'm closing this issue, but if you have any questions, let us know here and we can reopen it.

![image](https://github.com/tabulartools/dax-optimizer/assets/1957788/f24d7acc-bd74-4106-bb41-4df70277ee4b)
