### ISSUE TITLE
Internal error due to analysis of the model

### ISSUE THREAD

**Issue by MarcusWegener** [tabulartools/dax-optimizer#23]
### Describe the problem

Analyze the model and get the error "internal error".

### Power BI

Power BI Desktop Version Februar 2024

### Steps to reproduce the behavior

1. upload the VPAX file
2. analyze the model
3. internal error

### Screenshots

![image](https://github.com/tabulartools/dax-optimizer/assets/39794269/e3e4712f-c8e9-4370-aa9a-64774c1e2ca3)

### Anything else ?

Trace id: 0e2f9add-015f-1797-3c4a-a7f1ab117e2a

**Comment by marcosqlbi** [comment]
Thank you Marcus, we'll look into it as soon as possible!

**Comment by albertospelta** [comment]
@MarcusWegener We have identified the error, and we are working to resolve it. We will update you once the fix is deployed in production.

**Comment by albertospelta** [comment]
@MarcusWegener The fix has been deployed in production, and now you can [re-run the analysis on the model](https://docs.daxoptimizer.com/glossary/re-run). I'm closing this issue, but if you encounter any further problems, please feel free to post here, and we can reopen it.
