### ISSUE TITLE
Enable MS Group Sharing: Transfer account from email login to Microsoft Work sign?

### ISSUE THREAD

**Issue by rmss-tech** [tabulartools/dax-optimizer#24]
### Describe the problem

I have created an account and subscription with my email address.  I am interested in sharing (read/write/edit) the subscription with a few people in my organization.  I understand that one can do this via the Settings > Groups tab and also requires a Microsoft Work account login.

How do I enable this feature by associating my Microsoft Work account to my current login or converting my subscription to a Microsoft Work account login?

### Power BI

n/a

**Comment by marcosqlbi** [comment]
Thanks for raising the issue. We must manage this process internally. Please, write to info@tabulartools.com and provide the information required about the account and the subscription you want to move from a email/password account to a work account, so we will be able to support you directly!
