### ISSUE TITLE
Model Not Supported By The Current Version Of The Service Or Is Invalid

### ISSUE THREAD

**Issue by tylerjtaub** [tabulartools/dax-optimizer#26]
### Describe the problem

After uploading my Vertipaq file, I am receiving the following error:
<img width="202" alt="image" src="https://github.com/tabulartools/dax-optimizer/assets/96488843/d9ed2eba-736c-4268-936e-b1f0f380d1cc">

### Power BI

Tabular Editor 3.15.0, PowerBI 2.128.1380.0 64-bit (April 2024)

### Steps to reproduce the behavior

1. Open model from DB in TE3
2. Connect to model through workspace XMLA endpoint
3. Collect states and export VertiPaq file
4. Upload VertiPaq file to Dax Optimizer
5. Receiver error when trying to anaylze file
<img width="202" alt="image" src="https://github.com/tabulartools/dax-optimizer/assets/96488843/c99c2403-4da3-4879-81ea-27dbd845bcc9">

### Screenshots

<img width="590" alt="image" src="https://github.com/tabulartools/dax-optimizer/assets/96488843/b7cfcb70-5f0e-4f54-b7f5-8fd804ccb577">

**Comment by albertospelta** [comment]
@tylerjtaub Thanks for reporting, we're currently investigating this.

**Comment by albertospelta** [comment]
@tylerjtaub The issue might arise from the VPAX file not containing the minimum information required for analysis. Could you please verify if the `ReadStatistics from data` and `Read statistics from DirectQuery tables` flags are enabled in TabularEditor settings ? Additionally, if the model includes Direct Lake partitions, it's also required to set `Statistics from Direct Lake models` to `Full`

![image](https://github.com/tabulartools/dax-optimizer/assets/1957788/64329217-131f-4257-9027-294825baab42)

**Comment by tylerjtaub** [comment]
That worked! Thank you.
