### ISSUE TITLE
Tried DAX Optimizer for the first time, got Not Valid / corrupted data.

### ISSUE THREAD

**Issue by ScottThompsonNH** [tabulartools/dax-optimizer#34]
### Describe the problem

I tried to analyze my model with DAX Optimizer.  I connected via open model from db.  I chose "Use obfuscation" in the settings.  But I end up with the message "Unable to download DAX Optimizer results: File contains corrupted data." in TE and the online tool shows "Not Valid".

### Power BI

TE 3.18.0, connected to model deployed to Power BI (PPU)

### Steps to reproduce the behavior

Connect to model from DB
Select "Use obfuscation" in options
Upload, wait a while then error.

### Anything else ?

Trace id: fb1bf276-f35a-4230-c400-db51e84710b3

**Comment by marcosqlbi** [comment]
Please, check two things.
First, enable "Read statistics from data" in VertiPaq Analyzer settings:
![image](https://github.com/user-attachments/assets/0b2f53de-3f34-49f0-935d-68a4b0a5f0b8)

Second, make sure the model does not have unprocessed partitions/columns, we are collecting reports of this type of issue which does not have a good diagnostic in the current version.

Please, let us know the result, thanks!

**Comment by albertospelta** [comment]
@ScottThompsonNH It appears that the error you are experiencing is likely the same one reported in [issue #33](https://github.com/tabulartools/dax-optimizer/issues/33). Could you please try the suggestions mentioned in [this comment](https://github.com/tabulartools/dax-optimizer/issues/33#issuecomment-2452578850) and let us know if they help resolve the issue? Thank you!

**Comment by ericdao-fin** [comment]
I checked the Vertipak "Read statistic data" and run Vertipak Analyzer to check if any partitions are not refreshed, calculated. No errors shown on Vertipak Analyzer. Then I click Options, Upload as New Version then click OK. The same error "corrupted data" happens, so it hasn't been solved yet.

![image](https://github.com/user-attachments/assets/c94cc31e-3b8b-4675-8e57-2058d3e4decc)

However, I exported the vpax file from TE3 and can upload it sucessfully via DAX Optimizer website.

**Comment by albertospelta** [comment]
Thank you, @ericdao-fin, for trying out the suggestion. We are aware of this issue and are working to resolve it. In the meantime, could you please confirm if you are able to analyze your model and then browse the results in Tabular Editor 3 after following these steps?

- Ensure that the Read Statistics options in the VertiPaq Analyzer preferences are enabled, as shown in the image below
![image](https://github.com/user-attachments/assets/02bd8d02-4059-45e9-b141-1f62fdfb1652)

- Collect the statistics and export the VPAX file to disk using the VertiPaq Analyzer integration in TE3
![image](https://github.com/user-attachments/assets/2a58bbb9-feaf-4476-b5c6-fa5d8bf45ede)

- Upload the extracted vpax file to DAX Optimizer using the website
![image](https://github.com/user-attachments/assets/020cd91e-f09b-4f8e-bb51-f11c0a618bd5)

- Run the analysis via the DAX Optimizer integration in TE3 and check the analysis results.
![image](https://github.com/user-attachments/assets/0786601d-166c-4b1c-a305-711de1a3265d)

Thank you, and we look forward to your confirmation!

**Comment by ericdao-fin** [comment]
hi, yes confirmed I did all the above steps succesfully. Thanks.

**Comment by ScottThompsonNH** [comment]
I had "Read statistics from data" enabled.
I do have a handful of incomplete partitions, later I will process them (it's a dev model).
Regardless, I was able to collect stats and export VPAX manually (both obfuscated and not) in TE and upload via the Dax Optimizer web app where it was able to analyze successfully.  I never get an "Unable to collect stats" message.

**Comment by albertospelta** [comment]
@ScottThompsonNH Thank you for letting us know. In your case, it's likely that the objects requiring recalculation are not being used by the queries that extract the statistics, which is why no error message is generated. We are currently working on resolving the issue causing the 'File contains corrupted data' error, and we'll update you as soon as the fix is available. Thanks!

**Comment by albertospelta** [comment]
@ScottThompsonNH This issue has been resolved in the latest release of TE3 [version 3.18.1](https://docs.tabulareditor.com/te3/other/release-notes/3_18_1.html). Please make sure to install this version.

We'll close the issue, but if you need any further assistance, feel free to comment here, and we can reopen it.
