### ISSUE TITLE
File contains corrupted data

### ISSUE THREAD

**Issue by ericdao-fin** [tabulartools/dax-optimizer#35]
### Describe the problem

Error for 1st run of DAX Optimizer via TE3

### Power BI

TE3 3.18.0.5749

### Steps to reproduce the behavior

1. Connect to PBI model on PBI Service (Premium Capacity)
2. Upload VPAX file to DAX Optimizer
3. Click Analyze
4. Bottom status shows File contains corrupted data

### Screenshots

![image](https://github.com/user-attachments/assets/352e0587-2ca4-40a0-9add-a11afab843ff)

![image](https://github.com/user-attachments/assets/47e32d9e-1f64-4eee-b8fa-2a7e8be25cc3)

### Anything else ?

Trace id: 96d0c29b-f4c5-761b-22d0-0f73ab6fb081

**Comment by marcosqlbi** [comment]
Please, check two things.
First, enable "Read statistics from data" in VertiPaq Analyzer settings (see #34 )

Second, make sure the model does not have unprocessed partitions/columns, we are collecting reports of this type of issue which does not have a good diagnostic in the current version.

Please, let us know the result, thanks!

**Comment by albertospelta** [comment]
@ericdao-fin It appears that the error you are experiencing is likely the same one reported in https://github.com/tabulartools/dax-optimizer/issues/33. Could you please try the suggestions mentioned in https://github.com/tabulartools/dax-optimizer/issues/33#issuecomment-2452578850 and let us know if they help resolve the issue? Thank you!

**Comment by albertospelta** [comment]
Hi @ericdao-fin! We are closing this issue as the fix has been released in the latest version of TE3 [3.18.1](https://docs.tabulareditor.com/te3/other/release-notes/3_18_1.html).
If you need any further assistance, feel free to comment here, and we can reopen the issue.
