### ISSUE TITLE
Tabular Editor 3 Enterprise Edition - Do not have runs available

### ISSUE THREAD

**Issue by BigStackSlack** [tabulartools/dax-optimizer#36]
### Describe the problem

I entered the redemption code associated with my TE3 Enterprise license, but am not able to run the Optimizer.  In settings, the license says it's active and there are 4 runs per day, however, upon attempting to run I receive the message, "You do not have enough runs available in this contract to perform a new analysis."  

### Power BI

Oct '24 Desktop

**Comment by albertospelta** [comment]
@BigStackSlack Could you please send an email to support@tabulartools.com, referencing this GitHub issue and indicating the username of your Dax Optimizer account? This will allow us to investigate the issue further. Thanks!

**Comment by albertospelta** [comment]
We are closing this issue. As mentioned offline, multiple licenses were available, and the model being analyzed was associated with a DAX Optimizer license different from the one provided with the TE3 Enterprise license.
