### ISSUE TITLE
Unable to Analyze model 

### ISSUE THREAD

**Issue by devaccount89** [tabulartools/dax-optimizer#38]
### Describe the problem

Error 500: Failed to fetch.
GET /v1/vpax/251671487440-599bd3d2-d914-458c-8a9c-6ad19491d1b7/251671486920-ffb042eb-d615-4fc9-b71f-c2eea913ed75/251671486918-99ee46e9-b8e3-49e3-ae31-7d344cac80cb/file

### Power BI

PowerBI Premium P1 and Tabular Editor 3 3.18.0

### Steps to reproduce the behavior

Export vpax from TE 3 upload into app. analyze not working. 

### Anything else ?

Trace id: 070484ec045419b758ed79ee8fd9a9c7

**Comment by marcosqlbi** [comment]
@devaccount89, please can you check #37? It seems a similar issue is caused by an internal firewall/antivirus that intercepts the payload and violates security rules for the DAX Optimizer service.

**Comment by devaccount89** [comment]
Hi @marcosqlbi , 
Thanks for the fast reply. I will check internally and open a new bug in case needed. 
Thank you - and I will close this.
