### ISSUE TITLE
redemption code

### ISSUE THREAD

**Issue by sdevine-aya** [tabulartools/dax-optimizer#39]
### Describe the problem

created account before getting SSO approval - would like to combine the separate accounts or gain access to the TE3 redemption code again. Both accounts are using the same email address.

### Power BI

the latest one

**Comment by albertospelta** [comment]
Could you send an email to support@tabulartools.com with the usernames for both accounts and the associated email address so we can investigate further? Thank you!

**Comment by albertospelta** [comment]
We are closing this issue as the license has been successfully activated on the work account.
