### ISSUE TITLE
Select/unselect all issues in TE3 as in the web app

### ISSUE THREAD

**Issue by ricky7uio** [tabulartools/dax-optimizer#40]
### The feature request

I would like to be able to check/uncheck all issues in TE3 as it's possible in the web app:
![image](https://github.com/user-attachments/assets/91e13f94-f68a-4ad8-937c-17e88fa8eec6)
![image](https://github.com/user-attachments/assets/3c7c5330-88ca-4c28-94ea-cef2bc7dddd5)

In big measures, this makes easier to check the affected row/lines without all the measure code being highlighted at the same time. 

### Proposed solution

Add the same functionally to be able to unselect/select all issues.
Thank you

**Comment by marcosqlbi** [comment]
@ricky7uio you should submit this request to Tabular Editor issues here: https://github.com/TabularEditor/TabularEditor3/issues - this area is for issues in DAX Optimizer service or web app. Your request is specific to the Tabular Editor user interface!
Thank you!
