### ISSUE TITLE
after assigning license to group cok-dataenheden

### ISSUE THREAD

**Issue by andreas-arbejder** [tabulartools/dax-optimizer#41]
### Describe the problem

Error DO300000: Not Found.
The requested resource is not found.
GET /v1/contract/251670201538-67c76c9b-6f3f-4e38-beec-267ae3405d30

### Power BI

none

### Steps to reproduce the behavior

1. Assign license to group
2. After everything is setup, an error message appears in bottom right corner as in Additional context
3. When I check my licenses it does not say active

### Additional context

Error DO300000: Not Found.
The requested resource is not found.
GET /v1/contract/251670201538-67c76c9b-6f3f-4e38-beec-267ae3405d30
Trace id: 6d70b4533240f66264130f0111a5d6b5
DAX Optimizer v1.2.18

### Screenshots

<img width="657" alt="license inactive" src="https://github.com/user-attachments/assets/bfc0fa99-51af-44d0-843a-c8d35acca475">
<img width="656" alt="license resource" src="https://github.com/user-attachments/assets/9d0233b4-2779-4233-bfef-c343869ca65f">

### Anything else ?

Trace id: 6d70b4533240f66264130f0111a5d6b5

**Comment by albertospelta** [comment]
@aols0228 we are investigating the issue and will update you as soon as we identify the cause

**Comment by albertospelta** [comment]
@aols0228 The `Not Found` error may be related to an error that occurred during the account switching process. We are investigating this, but the newly activated license should still be usable. The license displayed, starting with `2bd43c1c-1c75`, is associated with your personal account and has been deactivated. The new license (`d6d45826-02dd-...`) has been successfully activated and should be visible once the [user is switched to the group](https://docs.daxoptimizer.com/how-to-guides/managing-groups#how-to-switch-to-a-group) you created. 

Please try refreshing the page, and then could you confirm if the group you created is visible in the top right corner of the screen, as shown in the image below? After selecting it, when you go back to the `Settings > Licenses` panel, do you see the new license (`d6d45826-02dd-...`)?

![image](https://github.com/user-attachments/assets/4ff6ad63-940c-4029-b6f1-59d0d2e16af3)

**Comment by andreas-arbejder** [comment]
@albertospelta thanks for your reply
After refreshing, in the group section, I can see that I am a member of the group.
But I still only see the inactive license and cannot perform model analyses.
<img width="474" alt="license" src="https://github.com/user-attachments/assets/916ffe0f-a1e1-4e18-aefd-d0ce241964f8">
<img width="469" alt="group" src="https://github.com/user-attachments/assets/e562fc90-8634-42f5-b8c8-906926856723">

**Comment by albertospelta** [comment]
@aols0228 In the menu at the top right of the DAX Optimizer window, you should see the two accounts you can access: your personal account and the group account. See the example image below, where my personal account is highlighted in red, and my group account is highlighted in green. Which one is currently active? To see the new license, you first need to select the group account](https://docs.daxoptimizer.com/how-to-guides/managing-groups#how-to-switch-to-a-group).

![image](https://github.com/user-attachments/assets/440e0589-4316-4ce2-8c83-d455fffe8427)

**Comment by andreas-arbejder** [comment]
Thanks it works
