### ISSUE TITLE
The analyze process systematically fails after 2~3 min.

### ISSUE THREAD

**Issue by aminegara** [tabulartools/dax-optimizer#48]
### Describe the problem

The analyze process systematically fails after 2~3 min.
I used a VPAX file exported from the last version of Bravo plugged on October version of PBI Desktop Model.
I tried with 2 differents models, same behaviour ..

### Power BI

Power BI Desktop version October 2024

**Comment by aminegara** [comment]
Resolved

**Comment by marcosqlbi** [comment]
@aminegara did you just try again?
@albertospelta do we have logs of service failure?

**Comment by albertospelta** [comment]
@marcosqlbi I am currently reviewing the logs but haven’t been able to identify the issue reported. @aminegara Could you let us know if you received any specific error message or if you have an error identifier, such as a trace ID? Is this issue related to the error reported in https://github.com/tabulartools/dax-optimizer/issues/47, or is it a different problem?
