### ISSUE TITLE
Analyzing Power BI Desktop dataset pbix file

### ISSUE THREAD

**Issue by thegerscheffect** [tabulartools/dax-optimizer#5]
### Describe the problem

Error 400: Vpax cannot be optimized (DO100011)
The Vpax cannot be optimized [Incompatible license].

### Power BI

Version: 2.120.963.0 64-bit (August 2023)

### Steps to reproduce the behavior

1. Create workspace
2. Add new version
3. Upload vpax file
4. Click agree to consume 1 run and then click the Analyze button
5. error message appears: "Vpax cannot be optimized (DO100011)
The Vpax cannot be optimized [Incompatible license]."

### Anything else ?

Trace id: 3b91c56d-7d75-ac1f-1a36-8e2361a04dbb

**Comment by marcosqlbi** [comment]
Which extraction tool and version are you using? (Tabular Editor, DAX Studio, Bravo, ...)
If you are not using the latest version, can you try an updated version of these tools?
We look forward to hearing from you!

**Comment by thegerscheffect** [comment]
I was using both tabular editor and DAX studio. Both were giving the same error. Both were out of date. Updated both and now everything is working as expected.

Thank you.
On Sep 11, 2023, at 3:31 AM, Marco Russo ***@***.***> wrote:

﻿

Note: This message originated from outside the FIU Faculty/Staff email system.


Which extraction tool and version are you using? (Tabular Editor, DAX Studio, Bravo, ...)
If you are not using the latest version, can you try an updated version of these tools?
We look forward to hearing from you!

**Comment by marcosqlbi** [comment]
Thanks for the feedback - we are working to improve the error message so that it is more clear that this could be the issue.
