### ISSUE TITLE
analysis failed due to an internal error

### ISSUE THREAD

**Issue by shawne004** [tabulartools/dax-optimizer#6]
### Describe the problem

1st run - uploaded vpax, then analyzed, return an failure due to an internal error.....

### Power BI

PBIX August 2023

### Anything else ?

Trace id: f605ddaf-2988-2a3f-8c97-f35138bdaaf2

**Comment by albertospelta** [comment]
@shawne004 Thanks for reporting. We're actively investigating and will update this issue.

**Comment by shawne004** [comment]
started a new version to analyze and had the same result.  Here is the trace log:  Trace id: a8efb74e-5bde-c2fa-b5b6-15643744f57e

**Comment by marcosqlbi** [comment]
We detected an issue caused by some expression in the model, probably. @albertospelta will update you when the fix is deployed to production, then you should be able to run without errors. Thanks!

**Comment by shawne004** [comment]
It has worked!!!  Thank you!!!

Shawn Egan
615-428-8625
________________________________
