### ISSUE TITLE
Can not sign in to account

### ISSUE THREAD

**Issue by MilkoDurlevic** [tabulartools/dax-optimizer#8]
### Describe the problem

Error 500: HTTP Error 500.30 - ASP.NET Core app failed to start 
        
    
    
         HTTP Error 500.30 - ASP.NET Core app failed to start 

         Common solutions to this issue: The app failed to startThe app started but then stoppedThe app started but threw an exception during startup

        

         Troubleshooting steps: 
        
             Check the system event log for error messages 
             Enable logging the application process' stdout messages 
      [truncated]

### Power BI

Power Bi Desktop version August 2023

### Anything else ?

Trace id: 44b0a482-a533-43b4-36b7-9d73f1c1fc1d

**Comment by marcosqlbi** [comment]
Thanks for submitting the issue - we are investigating and it could be a transient issue, but we are verifying whether it depends on our infrastructure or on Azure services. Please, can you try again now and see whether the authentication now works?

**Comment by MilkoDurlevic** [comment]
This is resolved. Thanks
